-- MySQL Script generated by MySQL Workbench
-- 09/20/16 16:20:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema programathon2016
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema programathon2016
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `programathon2016` DEFAULT CHARACTER SET utf8 ;
USE `programathon2016` ;

-- -----------------------------------------------------
-- Table `programathon2016`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`pais` (
  `Id` INT(11) NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Iso` VARCHAR(2) NOT NULL,
  `Iso3` VARCHAR(3) NULL DEFAULT NULL,
  `CodigoNumerico` INT(11) NULL DEFAULT NULL,
  `CodigoTelefono` INT(11) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`estado` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` CHAR(50) NOT NULL,
  `PaisID` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_STATE_COUNTRY_idx` (`PaisID` ASC),
  CONSTRAINT `FK_STATE_COUNTRY`
    FOREIGN KEY (`PaisID`)
    REFERENCES `programathon2016`.`pais` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`genero` (
  `Id` VARCHAR(1) NOT NULL,
  `Nombre` CHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`sector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`sector` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` CHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`usuario` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(50) NOT NULL,
  `NombreCompleto` VARCHAR(100) NOT NULL,
  `Clave` VARCHAR(50) NOT NULL,
  `EmailContacto` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`pyme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`pyme` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `NombreComercio` CHAR(100) NOT NULL,
  `EstadoID` INT(11) NOT NULL,
  `SectorID` INT(11) NOT NULL,
  `AnnoInicioOperaciones` TINYINT(4) NOT NULL,
  `NumeroTelefono` CHAR(50) NOT NULL,
  `Direccion` CHAR(200) NOT NULL,
  `EsActiva` BIT(1) NOT NULL,
  `EsNegocioFamiliar` BIT(1) NULL DEFAULT NULL,
  `Logo` BLOB NOT NULL,
  `ExtensionLogo` CHAR(3) NOT NULL,
  `FechaCreacion` DATETIME NOT NULL,
  `FechaUltimaActualizacion` DATETIME NOT NULL,
  `EsFacebookAppInstalado` BIT(1) NOT NULL,
  `UsuarioID` INT(11) NOT NULL,
  `GeneroPropietarioID` VARCHAR(1) NOT NULL,
  `CedJuridica` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `FK_PYME_SECTOR_idx` (`SectorID` ASC),
  INDEX `FK_PYME_STATE_idx` (`EstadoID` ASC),
  INDEX `FK_PYME_USER_idx` (`UsuarioID` ASC),
  INDEX `FK_PYME_GENDER_idx` (`GeneroPropietarioID` ASC),
  CONSTRAINT `FK_PYME_GENDER`
    FOREIGN KEY (`GeneroPropietarioID`)
    REFERENCES `programathon2016`.`genero` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PYME_SECTOR`
    FOREIGN KEY (`SectorID`)
    REFERENCES `programathon2016`.`sector` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PYME_STATE`
    FOREIGN KEY (`EstadoID`)
    REFERENCES `programathon2016`.`estado` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PYME_USER`
    FOREIGN KEY (`UsuarioID`)
    REFERENCES `programathon2016`.`usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`tiporedsocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`tiporedsocial` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`redsocial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`redsocial` (
  `TipoRedSocialID` INT(11) NOT NULL,
  `Comentario` VARCHAR(300) NULL DEFAULT NULL,
  `InformacionContacto` VARCHAR(300) NULL DEFAULT NULL,
  `PymeID` INT(11) NOT NULL,
  `Link` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`TipoRedSocialID`, `PymeID`),
  INDEX `FK_SocialNetwork_Type_idx` (`TipoRedSocialID` ASC),
  INDEX `FK_SOCIALNETWORK_PYME_idx` (`PymeID` ASC),
  CONSTRAINT `FK_SOCIALNETWORK_PYME`
    FOREIGN KEY (`PymeID`)
    REFERENCES `programathon2016`.`pyme` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SOCIALNETWORK_TYPE`
    FOREIGN KEY (`TipoRedSocialID`)
    REFERENCES `programathon2016`.`tiporedsocial` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `programathon2016`.`respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programathon2016`.`respuesta` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Respuesta01` INT(11) NOT NULL,
  `Respuesta02` INT(11) NOT NULL,
  `Respuesta03` INT(11) NOT NULL,
  `Respuesta04` INT(11) NOT NULL,
  `Respuesta05` INT(11) NOT NULL,
  `FechaRespuesta` DATETIME NOT NULL,
  `GeneroID` VARCHAR(1) NOT NULL,
  `Campo01` VARCHAR(100) NULL DEFAULT NULL,
  `Campo02` VARCHAR(100) NULL DEFAULT NULL,
  `RangoEdad` TINYINT(1) NOT NULL,
  `PymeID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_ANSWER_GENDER_idx` (`GeneroID` ASC),
  INDEX `FK_RESPUESTA_PYME_idx` (`PymeID` ASC),
  CONSTRAINT `FK_ANSWER_GENDER`
    FOREIGN KEY (`GeneroID`)
    REFERENCES `programathon2016`.`genero` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESPUESTA_PYME`
    FOREIGN KEY (`PymeID`)
    REFERENCES `programathon2016`.`pyme` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
